substitutions:
  _IMAGE: us-central1-docker.pkg.dev/PROJECT/REPOSITORY/probe-managed-worker-pool:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - scripts/deploy/managed-cloud-run-worker-pool/Dockerfile
      - --tag
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}
